In [1]:
import numpy as np
import pandas as pd
import os
import re

import nltk.corpus
from nltk.corpus import stopwords
from nltk.util import ngrams
from nltk import word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
nltk.download('wordnet')

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.spatial import distance
from numpy.linalg import norm

import time

#from multiprocessing.pool import ThreadPool as Pool
#from multiprocessing import *


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\swani\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
os.chdir(r"C:\Users\swani\Python Projects\Case Bucket\Data")

In [3]:
data = pd.read_excel('N-Grams Data All Articles.xlsx')
length = int(len(data))
print('Data Length: %d' %(length))
print(data.head())

Data Length: 125831
   Unnamed: 0      Name  Article Number                          N-Grams
0           0  20467935          538672            vhdl get csgmss error
1           1  20467935          538672            get csgmss error data
2           2  20467935          538672           csgmss error data type
3           3  20467935          538672       error data type unresolved
4           4  20467935          538672  data type unresolved std_ulogic


In [4]:
searchTerms = pd.read_excel('XceliumCD_Data.xlsx')
length = int(len(searchTerms))
print('Data Length: %d' %(length))
print(searchTerms.head())

df = pd.read_excel('ALl-keywords-2021.xlsx')
exceptions = df["Keywords Flagged by IT"].tolist()

Data Length: 2059
  Product                                         Search Term  \
0  Xcelium                           probe depth not working    
1  Xcelium  Using environment variables in a timing check ...   
2  Xcelium                              Simulation profiling    
3  Xcelium                               timescale overriding   
4  Xcelium                             conditionally stopping   

              N-Grams Search Results                Unnamed: 3  \
0             probe create top depth      depth 3 probe create   
1             used timing file tfile  option timing file tfile   
2          dump profiling data xmsim   dpi data type profiling   
3  timescale value module overriding                       NaN   
4       conditionally split log file                       NaN   

                        Unnamed: 4  KB Articles  Unnamed: 6  Unnamed: 7  \
0                              NaN   20489076.0  20493943.0         NaN   
1                              NaN   2048567

In [32]:
ngrmasList = []
kbArticles = []
cosineScore = []

extreme_start = time.time()

k = 0
for term in searchTerms['Search Term']:
    print(str(k)+']')
    start = time.time()
        
    a = term.lower()
    a = a.replace('[^\w\s]','')
    stop_words = stopwords.words('english')
    a = [word for word in a.split() if word not in (stop_words)]
    a = ' '.join(a)
    a = [word for word in a.split() if word not in (exceptions)]
    a = ' '.join(a)
    lmtzr = WordNetLemmatizer()
    lemmatized = [lmtzr.lemmatize(word) for word in word_tokenize(a)]
    a = ' '.join(lemmatized)
    print('Processed input: %s' %(a))

    ngrams = data['N-Grams']
    ngrams_list = ngrams.tolist()
    ngrams_list.append(a)

    vectorizer = TfidfVectorizer().fit_transform(ngrams_list)
    input_vector = vectorizer[-1]
    vectorizer = vectorizer[:-1]

    from sklearn.metrics.pairwise import linear_kernel
    cosine_similarities = linear_kernel(vectorizer[:], input_vector).flatten()

    sort_cs = np.sort(cosine_similarities)[::-1]
    top3_values = sort_cs[:3]
        
    if (any(i >= 0.8 for i in top3_values) is True):
        cosineScore.append(top3_values)

    else:
        top3_values = [0,0,0]
        cosineScore.append(top3_values)

    print(top3_values)
    
    indices_list = []
    
    if (all(i == 0 for i in top3_values) is True):
        indices_list = [0,0,0]
    else:
        for value in top3_values:
            max_list = [i for i,val in enumerate(cosine_similarities) if val==value]
            indices_list.append(max_list[0])
        
    print('The indices of the n-grams: %a'%indices_list)

    if (indices_list == [0,0,0]):
            kbArticles.append([])
            print('The KB Articles: None')
    else:
        lst = [data.iloc[i]['Name'] for i in indices_list]
        KB_Articles = np.unique(lst)
        print('The KB Articles: %a'%KB_Articles)
        kbArticles.append(KB_Articles)
        unique_indices = [lst.index(i) for i in KB_Articles]
    
    op_ngrams = []
    if (indices_list == [0,0,0]):
        op_ngrams.append('')
    else:
        for i in unique_indices:
            index = indices_list[i]
            op_ngrams.append(ngrams_list[index])
    print(op_ngrams)
    ngrmasList.append(op_ngrams)
    
    end = time.time()
    print('Time Taken to Respond: %d seconds' %(end-start))
    print('')
    k = k+1
    
extreme_end = time.time()
print('Time Taken for the whole code to Respond: %d seconds' %(extreme_end-extreme_start))

0]
Processed input: probe depth working
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1]
Processed input: using environment variable timing check tfile
[0.85193251 0.59995454 0.59915412]
The indices of the n-grams: [123534, 34987, 27805]
The KB Articles: array([20452070, 20485672, 20486602], dtype=int64)
['timing check using tfile', 'used timing file tfile', 'option timing file tfile']
Time Taken to Respond: 1 seconds

2]
Processed input: profiling
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

3]
Processed input: timescale overriding
[0.86433557 0.8599573  0.77640541]
The indices of the n-grams: [81427, 81443, 81442]
The KB Articles: array([20405661], dtype=int64)
['timescale value module overriding']
Time Taken to Respond: 1 seconds

4]
Processed input: conditionally stopping
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken 

[1. 1. 1.]
The indices of the n-grams: [20565, 20565, 20565]
The KB Articles: array([20480344], dtype=int64)
['sv_seghandler trapno 1 addr']
Time Taken to Respond: 1 seconds

46]
Processed input: dlcsmd worklib.specman : ncrunsv
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

47]
Processed input: getting undefined symbol abc.so file even though definition present file
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

48]
Processed input: verdi
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

49]
Processed input: running
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

50]
Processed input: trying verilog & vhdl file compile virtuoso 6.17 getting following
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond:

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

92]
Processed input: failed retrieve input data area evcd file
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

93]
Processed input: updating 19.03.002 imc tool give version mismatch
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

94]
Processed input: error : error processing stack frame ( 37 ) - skipping rest frame !
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

95]
Processed input: crash : xmsim : * f , scsig : signal sigfpe raised systemc library applicat
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

96]
Processed input: vmanager ( imc ) tool appears missing .
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

137]
Processed input: constant generated generate statement re-generated power-up lp corrup
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

138]
Processed input: http : //support.cadence.com/apex/articleattachmentportal ? id=a1od0000000nw0aeae & pagename=articleconte
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

139]
Processed input: extract file list ( with absolute path ) verilog/systemverilog source contributing
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

140]
Processed input: incremental elaba
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

141]
Processed input: multi clock property concurrent assertion
[0, 0, 0]
The indices of t

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

182]
Processed input: merge coverage result ?
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

183]
Processed input: error mean ? vm_scan.pl : log scan match file.\nlocal_log.log\nvm_s
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

184]
Processed input: system verilog top am
[0.82826207 0.59703012 0.58223581]
The indices of the n-grams: [47165, 47164, 82971]
The KB Articles: array([20416947, 20489621], dtype=int64)
['system verilog sv system', 'am design system verilog']
Time Taken to Respond: 1 seconds

185]
Processed input: if ( a === 1'bx ) working gls
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

186]
Processed input: sdf retain question
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB A

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

230]
Processed input: complains zero diagonal \
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

231]
Processed input: xmlib.lock
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

232]
Processed input: capture replay
[0.84341407 0.79002861 0.77408112]
The indices of the n-grams: [59634, 59635, 59633]
The KB Articles: array([20492025], dtype=int64)
['using capture replay feature']
Time Taken to Respond: 1 seconds

233]
Processed input: libindago
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

234]
Processed input: vhdl compile
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

235]
Processed input: access
[0.84301084 0.82254019 0.79328066]
The in

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

273]
Processed input: dump waveform without optimized
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

274]
Processed input: disable optimization generating waveform using recordfile recordvars
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

275]
Processed input: build_atpg.log - fork : allocate memory
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

276]
Processed input: am crashing 19.03 whereas passing 18.09
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

277]
Processed input: constant object marking coverage
[0.85805126 0.8183682  0.78269329]
The indices of the n-grams: [67143, 67144, 75975]
The KB Articles: array([20494657, 20497148], d

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

314]
Processed input: oracle linux w/red hat compatible kernel aforementioned application
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

315]
Processed input: sdf
[0.82423877 0.82420612 0.8051827 ]
The indices of the n-grams: [123559, 73823, 44691]
The KB Articles: array([20452071, 20488206, 20496684], dtype=int64)
['sdf block level sdf', 'sdf annotator u sdf', 'sdf time sdf done']
Time Taken to Respond: 1 seconds

316]
Processed input: unit delay mode particular hierarchy
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

317]
Processed input: \\-pathpulse option plus adding line specify part code like : \n\nspecify\n sp
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

318]
Processed input: unable poi

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

359]
Processed input: - mixed-signal cds_get_analog_value supported virtual interface
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

360]
Processed input: digital_mixed_signal_option
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

361]
Processed input: cds_get_analog_value uvm environment virtual interface monitor
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

362]
Processed input: disable negative timing check
[0.8083415  0.80699846 0.80699846]
The indices of the n-grams: [34599, 121570, 121570]
The KB Articles: array([20448746, 20486512], dtype=int64)
['negative timing timing check', 'negative timing check negative']
Time Taken to Respond: 1 seconds

363]
Processed input: nontcglitch
[0, 0, 0]
T

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

405]
Processed input: * e , trvof : simulated time overflow
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 2 seconds

406]
Processed input: crossing clock domain synchronizer properly showing behavior
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

407]
Processed input: merge vmanager
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

408]
Processed input: xilinx library csi
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

409]
Processed input: simvision issue : unable load snapshot error : ppesnap
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

410]
Processed input: default binding occurred c

[0.84441849 0.73768016 0.7268594 ]
The indices of the n-grams: [91317, 106686, 91316]
The KB Articles: array([11636072, 20186958], dtype=int64)
['hang low power lp', 'low power low power']
Time Taken to Respond: 2 seconds

452]
Processed input: run different directory
[0.89910537 0.88822268 0.63669271]
The indices of the n-grams: [110346, 110345, 99648]
The KB Articles: array([11273618, 20283094], dtype=int64)
['different directory source file', 'run different directory use']
Time Taken to Respond: 1 seconds

453]
Processed input: amsd : seeing numerical glitch
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

454]
Processed input: uvm_version
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

455]
Processed input: looking using ipxact2vrad.pl install running demo examp
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 2 se

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

498]
Processed input: bblist
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

499]
Processed input: export evcd
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

500]
Processed input: simvision advanceded
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

501]
Processed input: vhdl 2008 minimum
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

502]
Processed input: simvision advanced
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

503]
Processed input: lwd simvision
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

504]
Processed

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

543]
Processed input: trying save wreal signal fsdb .
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

544]
Processed input: scoreboard debug simvision
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

545]
Processed input: simvision slow lwd
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

546]
Processed input: xmvhdl_p : * e , atndes ( /bram_sdp_macro.vhd,1493|32 ) : attribute prefix appropriate designato
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

547]
Processed input: zlib
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

548]
Processed input: gls ntc3
[0, 0, 0]
The indices of 

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

591]
Processed input: xmshell amsilc vhdl analog
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

592]
Processed input: throwing instance 'std : :logic_error '
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

593]
Processed input: xmsim : * e , asrtst
[1.         1.         0.89127108]
The indices of the n-grams: [76856, 76856, 52156]
The KB Articles: array([20497432, 20500379], dtype=int64)
['1 xmsim e asrtst', 'output xmsim e asrtst']
Time Taken to Respond: 1 seconds

594]
Processed input: unable see functional coverage cover point coded inside class . currently adding funct
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

595]
Processed input: netlist run cpf/upf support .
[0, 0, 0]
The indices of t

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

637]
Processed input: license lost jaspergold
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

638]
Processed input: conditional breakpoint assert_output_stop_level tcl
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

639]
Processed input: assert_output_stop_level
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

640]
Processed input: cfeplm error switch
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

641]
Processed input: hanging compiling without going .
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

642]
Processed input: caught abort signal ! ! !
[0, 0, 0]
The indices of the n-gr

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

683]
Processed input: profiler - xprof database dump failed
[0.87589816 0.71513205 0.70989295]
The indices of the n-grams: [22342, 22341, 22270]
The KB Articles: array([20481181], dtype=int64)
['xprof database dump failed']
Time Taken to Respond: 1 seconds

684]
Processed input: error
[1. 1. 1.]
The indices of the n-grams: [4744, 4744, 4744]
The KB Articles: array([20471663], dtype=int64)
['c 3 2 error']
Time Taken to Respond: 1 seconds

685]
Processed input: makelib
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

686]
Processed input: check whether error downgraded
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

687]
Processed input: list softerrors xrun
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 secon

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

730]
Processed input: assertion fails end sim due
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

731]
Processed input: imc nt found
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

732]
Processed input: cds_globals path
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

733]
Processed input: compiled c .o .so file controlled ?
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

734]
Processed input: ucd file can not
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

735]
Processed input: merge ucd ucm
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to 

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

780]
Processed input: compare signal two
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

781]
Processed input: pas argument tcl file
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

782]
Processed input: tcl input line
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

783]
Processed input: installation linux seems ok can not configure iscape
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

784]
Processed input: base update
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

785]
Processed input: bit select
[0.86336477 0.77263339 0.76099023]
The indices of the n-grams: [28814, 105253, 105

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

825]
Processed input: le sdf annotation percentage seen pathdelays , whereas timing check 100 %
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

826]
Processed input: get system verilog netlist '\
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

827]
Processed input: xrun option sdf annotation xrun command-line option
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

828]
Processed input: assign real logic
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

829]
Processed input: save signal debug
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

830]
Processed input: access probe variable 

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

872]
Processed input: uvm dynamic array max size\
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

873]
Processed input: cdns-ieee
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

874]
Processed input: save state
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

875]
Processed input: random fault selection
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

876]
Processed input: tool : \txmvlog ( 64 ) \t19.09-s007\n hostname : whi-asia-blue -- batch -- worker -- c2-standard-60-4\n opera
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

877]
Processed input: ca n't see interface toggle usin

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

917]
Processed input: trying run am interactive mode . however debugging would like plot th
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

918]
Processed input: unable generate code coverage metric csv_export using imc batch mode .
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

919]
Processed input: unable export csv detail window
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

920]
Processed input: guide
[0.88207734 0.87099203 0.86991479]
The indices of the n-grams: [35719, 80901, 80917]
The KB Articles: array([20486739, 20502628], dtype=int64)
['simulator guide like guide', 'guide called simulator guide']
Time Taken to Respond: 1 seconds

921]
Processed input: xprop related issue regression
[0, 

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

960]
Processed input: running am encrypted spectre netlist
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

961]
Processed input: compiled read access turned
[1.         1.         0.80611873]
The indices of the n-grams: [65990, 65990, 6445]
The KB Articles: array([20472814, 20493998], dtype=int64)
['run read access turned', 'compiled read access turned']
Time Taken to Respond: 1 seconds

962]
Processed input: makefile vendor step ius . modify use xcelium .
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

963]
Processed input: finding force testbench signal
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

964]
Processed input: xmsvams : * e , invtde expecting keyword 'connectmodule '
[0, 0, 0]
The indi

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1006]
Processed input: suppress eillen error
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1007]
Processed input: xprop wrongly saying x
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1008]
Processed input: nowork working library defined
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1009]
Processed input: xmvlog : * f , nowork ( /pkg/cadence-xcelium-/19.03.007/i686-linux/tools/spectre/etc/ahdl/disciplines.vam
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1010]
Processed input: use xmgentb generate testbench evcd ?
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1011]
Proce

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1052]
Processed input: notimingcheck
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1053]
Processed input: ability get timing violation notifier event xrun.log file feedback timing test
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1054]
Processed input: vhdl2008 osvvm
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1055]
Processed input: dlcilib
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1056]
Processed input: caused by : java.io.eofexception : ssl peer shut incorrectly
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1057]
Processed input: failed durin run showing lic er

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1098]
Processed input: possible dump ucm database step xcelium ?
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1099]
Processed input: svperf
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1100]
Processed input: toggle coverage system verilog interface
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1101]
Processed input: overwrite snapshot value
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1102]
Processed input: libx11.so.6 : can not open shared object file : file directory
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1103]
Processed input: crash verdi traversing design 

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1142]
Processed input: cds_implicit_tmpdir
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1143]
Processed input: standard evcd
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1144]
Processed input: nc_force
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1145]
Processed input: -y switch .flt file give error
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1146]
Processed input: ncelab : * e , cuvmur ( /user1/2007/h_nemezawa/board/relmod/ucpu200_lattice/rtl/mbbfifo.v,42|22 ) : instanc
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1147]
Processed input: unresolved worklib
[0, 0, 

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1190]
Processed input: save restart snapshoot new start time point snapshot
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1191]
Processed input: second argument timeunit
[0.8593815  0.81667873 0.81667873]
The indices of the n-grams: [56280, 56279, 56279]
The KB Articles: array([20490654], dtype=int64)
['second argument timeunit keyword']
Time Taken to Respond: 1 seconds

1192]
Processed input: subspacemap uvm_reg_map reg_verifier
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1193]
Processed input: error reading multi-dimensional array
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1194]
Processed input: dlnord error elaboration , go away elaboramccodegen dlnord
[0, 0, 0]
The indices of the n-gr

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1233]
Processed input: error : unable allocate memory transition file slice variable transition index level ( read ) .
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1234]
Processed input: x propagation vhdl mixed language
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1235]
Processed input: open fsdb waveform
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1236]
Processed input: * e , dberr : error loading database file ./cov_work/scope/icc_7d9ce774_00000000.ucm : \n
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1237]
Processed input: xmelab : * e , cuvunf * e , cuvunf ( /fshydata/uxhyp/candle/azanide/rgpt/azanide_regr/azanide/digital

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1279]
Processed input: low power message -lps_1801_msg
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1280]
Processed input: lint negative infex
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1281]
Processed input: sdfnef can not annotate
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1282]
Processed input: initialize flipflops netlist
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1283]
Processed input: trouble compiling model eenet ? imported
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1284]
Processed input: installscape exce
[0, 0, 0]
The indices of the n-grams: [0, 0,

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1325]
Processed input: xcelium > database -open -shm -into w_cfp2.shm ht_loc_int_misr -default\ncreated default shm database
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1326]
Processed input: save restore
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1327]
Processed input: $ cds_set_temperature ( temp )
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1328]
Processed input: article ( 11742164 )
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1329]
Processed input: ld_library_path
[0.82319953 0.77757432 0.70654764]
The indices of the n-grams: [17112, 17111, 17114]
The KB Articles: array([20469160], dtype=int64)
['ld_library_path path_o

[0.8533531  0.81002619 0.77365941]
The indices of the n-grams: [42648, 42484, 3805]
The KB Articles: array([20471644, 20499519, 20499602], dtype=int64)
['assertion use following tcl', 'assertion summary tcl assertion', 'n tcl option assertion']
Time Taken to Respond: 0 seconds

1371]
Processed input: icadv12.3-64b.500.22
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1372]
Processed input: xmvlog : * e , namool design unit long ( 1023 character ximum )
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1373]
Processed input: suppress $ error
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1374]
Processed input: array interface
[0.88645401 0.75819159 0.75073685]
The indices of the n-grams: [92886, 67872, 47190]
The KB Articles: array([11681360, 20489621, 20494932], dtype=int64)
['interface port array interfac

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1415]
Processed input: pli fsdb
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1416]
Processed input: am monte carlo net saved waveform
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1417]
Processed input: coverage_top
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1418]
Processed input: /vobs/lpradar/modules/lpradar_top_ctrl/hdl/rtl/lpradar_top_ctrl_regs.v
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1419]
Processed input: generate vector file encrypted module boundary port debug purpose
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1420]
Processed input: omitting assign

[0.86328444 0.85532309 0.76140381]
The indices of the n-grams: [46397, 46396, 1719]
The KB Articles: array([20470867, 20489165], dtype=int64)
['access rwc read access', 'access rwc use irun']
Time Taken to Respond: 0 seconds

1460]
Processed input: setting window
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 1 seconds

1461]
Processed input: specifying xrun gui
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1462]
Processed input: failed generate netlist parent-child\ndatabase cellview
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1463]
Processed input: want add delay port sdf annotated
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1464]
Processed input: select_coverage
[0.93091632 0.93091632 0.82492161]
The indices of the n-grams: [109516, 109516, 10

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1506]
Processed input: design probed even though -probe -all used
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1507]
Processed input: illegal supply logic expression
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1508]
Processed input: fsdb output file split
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1509]
Processed input: internal exception error sv seghandler
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1510]
Processed input: getting
[0.83167704 0.81742287 0.7218985 ]
The indices of the n-grams: [70930, 27341, 2992]
The KB Articles: array([20471449, 20485582, 20495725], dtype=int64)
['design getting following f', 'getting err

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1551]
Processed input: outside engine
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1552]
Processed input: outside engine
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1553]
Processed input: pragma
[0.8430995  0.83311916 0.82954457]
The indices of the n-grams: [40692, 109694, 40741]
The KB Articles: array([20279107, 20498838], dtype=int64)
['supported pragma protect pragma', 'pragma use right pragma']
Time Taken to Respond: 0 seconds

1554]
Processed input: xrun create probe
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1555]
Processed input: trying reg_verifier provided /tools/cadence/xcelium_20.09.003/tools/sia/examples/
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
[

[0.87553433 0.76086255 0.70799814]
The indices of the n-grams: [118120, 118121, 118122]
The KB Articles: array([20381763], dtype=int64)
['version simulator version imc']
Time Taken to Respond: 0 seconds

1596]
Processed input: protected
[0.89654333 0.88434969 0.87409941]
The indices of the n-grams: [78179, 78177, 78178]
The KB Articles: array([20497516], dtype=int64)
['protected protected file generated']
Time Taken to Respond: 0 seconds

1597]
Processed input: constrain caused use function call rand argument . show
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1598]
Processed input: xrun : * e , nostupr : detected setup simulation . -r/-r < name > used
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1599]
Processed input: coverage report xml format toggle coverage
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1642]
Processed input: taken rtl file primary tb file incremental msie set up . need reuse
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1643]
Processed input: can not open instrumentation configuration file
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1644]
Processed input: msie multi step flow
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1645]
Processed input: design processor
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1646]
Processed input: simvision export schematic
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1647]
Processed input: generate vcd file
[0, 0, 0]

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1689]
Processed input: machine learning
[0.81202061 0.81202061 0.79083498]
The indices of the n-grams: [60711, 60711, 51837]
The KB Articles: array([20492449, 20500154], dtype=int64)
['logic simulator machine learning', 'machine learning coverage bin']
Time Taken to Respond: 0 seconds

1690]
Processed input: team , ca n't able find verplex daemon download . please share verplex daem
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1691]
Processed input: working flow enabling intel cth env .
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1692]
Processed input: e , cuvunf hierarchical component lookup failed
[0.86648054 0.86648054 0.86648054]
The indices of the n-grams: [4988, 4988, 4988]
The KB Articles: array([20471843], dtype=int64)
['hierarchical component 

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1734]
Processed input: get coverage local toggle coverage
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1735]
Processed input: per_instance coverage collected even used per_instance covergroup
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1736]
Processed input: connect module
[0.86762184 0.84815635 0.78854259]
The indices of the n-grams: [57767, 54836, 78702]
The KB Articles: array([20491450, 20497737, 20502353], dtype=int64)
['connect rule connect module', 'module actual connect module', 'connect module custom connect']
Time Taken to Respond: 0 seconds

1737]
Processed input: warning ! timing violation
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1738]
Processed input: within method starting

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1779]
Processed input: xmelab : * w , cusrch : resolved
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1780]
Processed input: xmsc_module_export
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1781]
Processed input: xmsc_module_export
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1782]
Processed input: signal toggled seem covered code coverage
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1783]
Processed input: \thow setup load pli vcd dumping 20.09
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1784]
Processed input: mda toggle coverage
[0.83078209 0.61690011 0.61690011]
T

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1825]
Processed input: vcs loopreport
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1826]
Processed input: view delta cycle waveform
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1827]
Processed input: cuvmur error
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1828]
Processed input: specman , e , override , test , constraint , sequence
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1829]
Processed input: training
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1830]
Processed input: training
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Ta

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1874]
Processed input: delta event waveform
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1875]
Processed input: expression coverage data imc
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1876]
Processed input: write one tcl procedure wait force ? f
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1877]
Processed input: write one tcl procedure wait force ?
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1878]
Processed input: trtovf : simulated time overflow .
[1.         1.         0.85590119]
The indices of the n-grams: [89202, 89202, 89201]
The KB Articles: array([1840958], dtype=int64)
['trtovf simulated time overflow']
Time Taken t

[0.84783747 0.80923908 0.78979543]
The indices of the n-grams: [37698, 11662, 11659]
The KB Articles: array([20484416, 20487547], dtype=int64)
['tchecks 4 annotated 10000', 'disabled tchecks 0 annotated']
Time Taken to Respond: 0 seconds

1919]
Processed input: q < = rising_edge ( clk ) ;
[0.90153641 0.89172029 0.83143356]
The indices of the n-grams: [29704, 119926, 119928]
The KB Articles: array([20444574, 20483101], dtype=int64)
['clk begin rising_edge clk', 'rising_edge clk q end']
Time Taken to Respond: 0 seconds

1920]
Processed input: power bar simvision
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1921]
Processed input: crash pdk srams
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1922]
Processed input: * f , svbdupi
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1923]
Processed input: loop�

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1964]
Processed input: xmsim csi
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1965]
Processed input: def param msie
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1966]
Processed input: get last n bit long double systemc
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1967]
Processed input: float modulus systemc
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

1968]
Processed input: interr
[0.93767946 0.80338282 0.79081442]
The indices of the n-grams: [69605, 69604, 11939]
The KB Articles: array([20484453, 20495272], dtype=int64)
['f interr error xrun', 'interr xmsim f interr']
Time Taken to Respond: 0 seconds

1969]
Processed input: ov

[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

2013]
Processed input: get source file signal path
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

2014]
Processed input: disable label
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

2015]
Processed input: move xcelium.d particular directory
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

2016]
Processed input: dfile
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

2017]
Processed input: axi vip documentation usage
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Time Taken to Respond: 0 seconds

2018]
Processed input: advanced profiling
[0, 0, 0]
The indices of the n-grams: [0, 0, 0]
The KB Articles: None
['']
Ti

In [35]:
datatoexcel = pd.ExcelWriter('test.xlsx')
  
df = pd.DataFrame(kbArticles)
# write DataFrame to excel
df.to_excel(datatoexcel)
  
# save the excel
datatoexcel.save()

In [36]:
df.shape

(2059, 3)

In [33]:
df = pd.DataFrame(kbArticles)

In [34]:
df

0           1           2
0            NaN         NaN         NaN
1     20452070.0  20485672.0  20486602.0
2            NaN         NaN         NaN
3     20405661.0         NaN         NaN
4            NaN         NaN         NaN
...          ...         ...         ...
2054         NaN         NaN         NaN
2055         NaN         NaN         NaN
2056         NaN         NaN         NaN
2057         NaN         NaN         NaN
2058  20470699.0         NaN         NaN

[2059 rows x 3 columns]